### ISSUE TITLE
[TODO] add ability to migrate tags

### ISSUE THREAD

**Issue by benediktg** [benediktg/wallabag-migration#1]
- [ ] extract info from tags and tags_entries tables
- [ ] merge them to a list
- [ ] attach this list to the article payload
